// Mapping function to convert demo IDs to image filenames
export function getDemoImagePath(demoId: string): string {
    // Map demo IDs to their corresponding image filenames
    const imageMapping: Record<string, string> = {
        'ai-dev-challenge': 'ai_dev_challenge_hub',
        'ambient-weather': 'ambient_weather_dashboard',
        'markdown-viewer': 'markdown_viewer',
        'festy-packer': 'festy_packer',
        'see-ya-there': 'seeyathere',
        'split-sumthin': 'split_sumthin',
        'ai-tools-lab-quiz': 'ai_tools_quiz',
        'toroidal-field': 'toroidal_field',
        'pspsps': 'pspsps',
        'camp-tribute': 'camp_tribute',
        'spr1nklr': 'spr1nklr',
        'devops-certified': 'devops_certified',
        'lissajous-demo': 'lissajous_curves',
        'jhand-tv': 'jhand_tv',
        'ignite-karaoke': 'ignite_karaoke',
        'vinyl-viewer': 'vinyl_viewer',
        'doggo-explorer': 'doggo_explorer',
        'lifx-app': 'lumapad',
        'ambient-weather-art': 'ambient_weather_art',
        'pomodoro-writer': 'PomodoroWriter',
        'video-scope': 'VideoScope',
        'do-it-lady': 'DoItLady',
        'bills-blitz': 'Bills_Blitz',
        'hero-scope': 'HeroScope',
        'collatz-conjecture': 'CollatzConjecture',
        'pokemon-battle': 'PokemonBattle',
        'openweathermap': 'OpenWeatherMap',
        'scam-url-detector': 'Scam_url_detector',
        'star-wars-trivia': 'StarWarsTrivia',
        'ms-learn-quiz': 'MSLearnQuiz',
        'keyboard-speed-test': 'KeyboardSpeedTest',
        'space-time-language': 'space-time-language',
        'zeta-3': 'zeta-3',
        'network-diagnostics': 'network-diagnostics',
        'btc-price-wrapper': 'btc-price-wrapper',
        'datadog-toto-simulator': 'datadog-toto-simulator',
        // New demos added
        'magic-eye-generator': 'magic_eye_generator',
        'vinyl-zenith': 'my_vinyl_collection',
        'lyric-lounge-ipad': 'pickinpartner',
        'guitar-triads': 'guitar_triads',
        'music-theory-lessons': 'music_theory_lessons',
        'technical-debt': 'technical_debt',
        'klein-bottle': 'klein_bottle',
        '3d-logo-viewer': '3d_logo_viewer',
        'perceptron': 'perceptron',
        'backpropagation': 'backpropagation',
        'stardust': 'stardust',
        'ai-energy-impact': 'ai_energy_consumption',
        'robots-txt-generator': 'robot_txt_generator',
        'faulty-deployment-detection': 'faulty_deployment_detection',
        'reservation-system': 'reservation_system',
        'ecco-ocean-visualization': 'ECCO'
    };

    const imageName = imageMapping[demoId] || demoId;
    return `/images/screenshots/${imageName}.png`;
} 